repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/python-poetry/poetry
    rev: "1.5.1"
    hooks:
      - id: poetry-check
  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c 'poetry run black .; git update-index --again'
        language: system
        types: [python]
      - id: ruff
        name: ruff
        entry: bash -c 'poetry run ruff . --fix; git update-index --again'
        language: system
        types: [python]
